apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-binding
  labels:
    app: jenkins
    tier: cicd
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
roleRef:
  kind: Role
  name: jenkins-deployer
  apiGroup: rbac.authorization.k8s.io


