apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-pv
  labels:
    app: logging
    purpose: elasticsearch-data
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    # Minikube hostPath directory for Elasticsearch indices.
    path: /mnt/data/logging


