apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
spec:
  containers:
    - name: cpu-stress
      image: polinux/stress
      command: ["stress-ng"]
      args: ["--cpu", "2", "--cpu-load", "100", "--timeout", "600s"]
      resources:
        requests:
          cpu: "500m"
        limits:
          cpu: "2000m"
  restartPolicy: Never

