apiVersion: v1
kind: Pod
metadata:
  name: pending-test
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "100"
          memory: "1000Gi"
        limits:
          cpu: "100"
          memory: "1000Gi"
  restartPolicy: Never

